export const MENUS=[
  {
    id:'dashboard',
    chineseName:'仪表盘',
    englishName:'dashboard',
    path:'wait',
    children:
      [
        {
          id:'config',
          chineseName:'配置',
          englishName:'config',
          path:'config'
        }
      ]
  },
  {
    id:'bot',
    chineseName:'机器人列表',
    englishName:'bot',
    path:'bot',
    children:
      [
        {
          id:'config',
          chineseName:'配置',
          englishName:'config',
          path:'config'
        }
      ]
  },
  {
    id:'skill',
    chineseName:'机器人技能',
    englishName:'skill',
    path:'wait',
    children:
      [
        {
          id:'config',
          chineseName:'配置',
          englishName:'config',
          path:'config'
        }
      ]
  },
  {
    id:'custom',
    chineseName:'定制服务',
    englishName:'custom',
    path:'wait',
    children:
      [
        {
          id:'config',
          chineseName:'配置',
          englishName:'config',
          path:'config'
        }
      ]
  },
  {
    id:'opinion',
    chineseName:'意见反馈',
    englishName:'opinion',
    path:'wait',
    children:
      [
        {
          id:'config',
          chineseName:'配置',
          englishName:'config',
          path:'config'
        }
      ]
  },
  {
    id:'authority',
    chineseName:'权限管理',
    englishName:'authority',
    path:'wait',
    children:
      [
        {
          id:'config',
          chineseName:'配置',
          englishName:'config',
          path:'config'
        }
      ]
  },
]
export const STR = {
  authority:'权限管理',
  custom:'定制服务',
  opinion:'意见反馈',
  bot:'机器人列表',
  skill:'机器人技能',
  dashboard:'仪表盘',
  create: '创建',
  edit: '编辑'
}
export const USERNAME = 'userName';
export const TOKEN = 'token';


